name: Check GitHub Secrets

on:
  workflow_dispatch:  # 只能手動觸發

jobs:
  check-secrets:
    name: Verify Required Secrets
    runs-on: ubuntu-latest
    
    steps:
    - name: Check all required secrets
      run: |
        echo "## 🔍 Checking GitHub Secrets Configuration"
        echo ""
        
        # Function to check if secret is set
        check_secret() {
          local secret_name=$1
          local secret_value=$2
          
          if [ -z "$secret_value" ]; then
            echo "❌ $secret_name is NOT set"
            return 1
          else
            # Don't print the actual value, just confirm it exists
            echo "✅ $secret_name is configured"
            return 0
          fi
        }
        
        # Track if any secret is missing
        MISSING_SECRETS=0
        
        echo "### Azure Credentials"
        check_secret "AZURE_CLIENT_ID" "${{ secrets.AZURE_CLIENT_ID }}" || MISSING_SECRETS=1
        check_secret "AZURE_CLIENT_SECRET" "${{ secrets.AZURE_CLIENT_SECRET }}" || MISSING_SECRETS=1
        check_secret "AZURE_SUBSCRIPTION_ID" "${{ secrets.AZURE_SUBSCRIPTION_ID }}" || MISSING_SECRETS=1
        check_secret "AZURE_TENANT_ID" "${{ secrets.AZURE_TENANT_ID }}" || MISSING_SECRETS=1
        
        echo ""
        echo "### Container Registry"
        check_secret "ACR_USERNAME" "${{ secrets.ACR_USERNAME }}" || MISSING_SECRETS=1
        check_secret "ACR_PASSWORD" "${{ secrets.ACR_PASSWORD }}" || MISSING_SECRETS=1
        
        echo ""
        echo "### Azure OpenAI"
        check_secret "AZURE_OPENAI_ENDPOINT" "${{ secrets.AZURE_OPENAI_ENDPOINT }}" || MISSING_SECRETS=1
        check_secret "AZURE_OPENAI_API_KEY" "${{ secrets.AZURE_OPENAI_API_KEY }}" || MISSING_SECRETS=1
        check_secret "EMBEDDING_ENDPOINT" "${{ secrets.EMBEDDING_ENDPOINT }}" || MISSING_SECRETS=1
        check_secret "COURSE_EMBEDDING_ENDPOINT" "${{ secrets.COURSE_EMBEDDING_ENDPOINT }}" || MISSING_SECRETS=1
        
        echo ""
        echo "### Application Secrets"
        check_secret "JWT_SECRET_KEY" "${{ secrets.JWT_SECRET_KEY }}" || MISSING_SECRETS=1
        check_secret "CONTAINER_APP_API_KEY" "${{ secrets.CONTAINER_APP_API_KEY }}" || MISSING_SECRETS=1
        
        echo ""
        echo "---"
        echo ""
        
        if [ $MISSING_SECRETS -eq 0 ]; then
          echo "🎉 **All required secrets are configured!**"
          echo ""
          echo "Your GitHub Actions workflows should work properly."
        else
          echo "⚠️ **Some secrets are missing!**"
          echo ""
          echo "Please configure the missing secrets in:"
          echo "Settings → Secrets and variables → Actions"
          echo ""
          echo "Refer to docs/GITHUB_SECRETS_SETUP.md for detailed instructions."
          exit 1
        fi